version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: oda-postgres-dev
    environment:
      POSTGRES_DB: oda_dev
      POSTGRES_USER: oda_user
      POSTGRES_PASSWORD: oda_password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - oda-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U oda_user -d oda_dev']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: oda-redis-dev
    command: redis-server --appendonly yes --requirepass redis_password
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - oda-network
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: oda-elasticsearch-dev
    environment:
      - node.name=oda-es-node
      - cluster.name=oda-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - oda-network
    healthcheck:
      test:
        ['CMD-SHELL', 'curl -f http://localhost:9200/_cluster/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: oda-kibana-dev
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    ports:
      - '5601:5601'
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - oda-network
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:5601/api/status || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: oda-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: oda_user
      RABBITMQ_DEFAULT_PASS: oda_password
      RABBITMQ_DEFAULT_VHOST: oda_vhost
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - oda-network
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: oda-minio-dev
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: oda_minio_user
      MINIO_ROOT_PASSWORD: oda_minio_password
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    networks:
      - oda-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  storybook:
    build:
      context: ..
      dockerfile: Dockerfile.storybook
      target: development
    container_name: oda-storybook-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - '6006:6006'
    volumes:
      - ../apps/frontend/src:/app/src
      - ../apps/frontend/.storybook:/app/.storybook
    networks:
      - oda-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  rabbitmq_data:
    driver: local
  minio_data:
    driver: local

networks:
  oda-network:
    driver: bridge
